"""Update

Revision ID: 523a490f5919
Revises: d92ad12b64ce
Create Date: 2024-09-13 23:17:12.961597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523a490f5919'
down_revision = 'd92ad12b64ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.String(length=80), nullable=False),
    sa.Column('transaction_comment', sa.String(length=256), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('offset_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions_statement')
    # ### end Alembic commands ###
