"""Add transactions statement

Revision ID: d92ad12b64ce
Revises: f329e1b3b2c8
Create Date: 2024-09-13 22:52:53.297510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92ad12b64ce'
down_revision = 'f329e1b3b2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.String(length=80), nullable=False),
    sa.Column('transaction_comment', sa.String(length=256), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('offset_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
